version: '2'

services:
  api:
    build:
      context: docker/php
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
      DEMO_API_ENV: dev
    ports:
      - 8080:8080
    volumes:
      - .:/var/www
  test:
    build:
      context: docker/php
    working_dir: /var/www
    command: php -S 0.0.0.0:8081 -t public
    environment:
      DEMO_API_ENV: test
    ports:
      - 8081:8081
    volumes:
      - .:/var/www
